version: '3.3'

volumes:
  mwop_net_redis:
  mwop_net_shared_data:

services:
  redis:
    image: redis
    expose:
      - "6379"
    volumes:
      - ./etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - mwop_net_redis:/data
    logging:
      options:
        max-size: 50m

  php:
    build: 
      context: .
      dockerfile: .docker/php.Dockerfile
    env_file:
      - .env
    depends_on:
      - worker
      - redis
    volumes:
      - mwop_net_shared_data:/var/www/data/shared
      - ./.docker/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./.docker/etc/zendphp/conf.d/mwop.ini:/etc/zendphp/conf.d/99-mwop.ini
      - ./.docker/etc/nginx/nginx.conf:/etc/nginx/nginx.con
      - ./.docker/s6/cont-init.d/00-build.sh:/etc/cont-init.d/00-build.sh
      - ./.docker/s6/cont-init.d/01-std-stream-permissions.sh:/etc/cont-init.d/01-std-stream-permissions.sh
      - ./.docker/s6/cont-init.d/99-start-message.sh:/etc/cont-init.d/99-start-message.sh
      - ./config:/var/www/config
      - ./data:/var/www/data
      - ./public:/var/www/public
      - ./src:/var/www/src
      - ./templates:/var/www/templates
      - ./vendor:/var/www/vendor
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
    logging:
      options:
        max-size: 50m

  worker:
    build: 
      context: .
      dockerfile: .docker/worker.Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - mwop_net_shared_data:/var/www/data/shared
      - ./.docker/etc/zendphp/conf.d/mwop.ini:/etc/zendphp/conf.d/99-mwop.ini
      - ./.docker/etc/supervisord/supervisord.conf:/etc/supervisord/supervisord.conf
      - ./.docker/s6/cont-init.d/00-worker-build.sh:/etc/cont-init.d/00-worker-build.sh
      - ./.docker/s6/cont-init.d/01-worker-pidfile-permissions.sh:/etc/cont-init.d/01-worker-pidfile-permissions.sh
      - ./.docker/s6/cont-init.d/01-std-stream-permissions.sh:/etc/cont-init.d/01-std-stream-permissions.sh
      - ./.docker/s6/cont-init.d/99-start-message.sh:/etc/cont-init.d/99-start-message.sh
      - ./.docker/s6/services.d/supervisor:/etc/services.d/supervisor
      - ./config:/var/www/config
      - ./data:/var/www/data
      - ./public:/var/www/public
      - ./src:/var/www/src
      - ./templates:/var/www/templates
      - ./vendor:/var/www/vendor
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
    logging:
      options:
        max-size: 50m

  nginx:
    build: 
      context: .
      dockerfile: .docker/nginx.Dockerfile
    env_file:
      - .env
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./.docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/etc/nginx/mime.types:/etc/nginx/mime.types
      - ./.docker/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./assets/dist:/var/www/public/assets
      - ./public/23ED29DA.asc:/var/www/public/23ED29DA.asc
      - ./public/images:/var/www/public/images
      - ./public/favicon.ico:/var/www/public/favicon.ico
      - ./public/index.php:/var/www/public/index.php
      - ./public/manifest.json:/var/www/public/manifest.json
    logging:
      options:
        max-size: 50m
