version: '3.3'

volumes:
  mwop_net_redis:
    external: true
  mwop_net_shared_data:
    external: true

services:
  redis:
    image: redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - ./.docker/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - mwop_net_redis:/data
    logging:
      options:
        max-size: 50m
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  php:
    build: 
      context: .
      dockerfile: .docker/php.prod.Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - zendhq
      - redis
    volumes:
      - mwop_net_shared_data:/var/www/data/shared
      - /etc/localtime:/etc/localtime:ro
    logging:
      options:
        max-size: 50m
    healthcheck:
      test: /usr/local/bin/fpm-healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  zendhq:
    image: cr.zend.com/zendhq:alpine-3.18
    user: zendphp
    volumes:
      - /etc/zendhq/license:/opt/zend/zendphp/etc/license
    ports:
      - "10091:10091"

  nginx:
    build: 
      context: .
      dockerfile: .docker/nginx.prod.Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - "9001:80"
    logging:
      options:
        max-size: 50m
    healthcheck:
      test: curl --fail http://localhost/.health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
