version: '3.3'

services:
  redis:
    image: redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - ./etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - mwop_net_redis:/data
    logging:
      options:
        max-size: 50m
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  php:
    build: 
      context: .
      dockerfile: etc/docker/php.Dockerfile
      args:
        INSTALL_COMPOSER: 'true'
        SYSTEM_PACKAGES: 'cron'
        ZEND_EXTENSIONS_LIST: 'bz2 curl intl mbstring opcache sqlite3 tidy xsl zip'
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "9001:9001"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./config:/var/www/config
      - ./data:/var/www/data
      - ./etc/cron.d/mwopnet:/etc/cron.d/mwopnet
      - ./etc/php/mwop.ini:/etc/zendphp/cli/conf.d/mwop.ini
      - ./src:/var/www/src
      - ./templates:/var/www/templates
      - ./public/23ED29DA.asc:/var/www/public/23ED29DA.asc
      - ./public/images:/var/www/public/images
      - ./public/favicon.ico:/var/www/public/favicon.ico
      - ./public/index.php:/var/www/public/index.php
      - ./public/manifest.json:/var/www/public/manifest.json
      - ./s6/cont-init.d/00-build.sh:/etc/cont-init.d/00-build.sh
      - ./s6/cont-init.d/01-std-stream-permissions.sh:/etc/cont-init.d/01-std-stream-permissions.sh
      - ./s6/cont-init.d/99-start-message.sh:/etc/cont-init.d/99-start-message.sh
      - ./s6/fix-attrs.d/app:/etc/fix-attrs.d/app
      - ./s6/fix-attrs.d/crond:/etc/fix-attrs.d/crond
      - ./s6/services.d/cron:/etc/services.d/cron
      - ./s6/services.d/swoole:/etc/services.d/swoole
    logging:
      options:
        max-size: 50m
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9001/api/ping']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  mwop_net_redis:
    external: true
