version: '3.3'

services:
  redis:
    build:
      context: .
      dockerfile: etc/docker/redis.Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - ./etc/redis/redis.docker.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis:/data
    logging:
      options:
        max-size: 50m

  php:
    build: 
      context: .
      dockerfile: etc/docker/php.Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/var/www
      - ./assets/build/css:/var/www/public/css
      - ./assets/build/js:/var/www/public/js
      - ./etc/php/mwop.ini:/usr/local/etc/php/conf.d/mwop.ini
      - ./etc/cron.d/mwopnet:/etc/cron.d/mwopnet
      - ./etc/bin/php-entrypoint:/usr/local/bin/entrypoint
    logging:
      options:
        max-size: 50m

  caddy:
    build:
      context: .
      dockerfile: etc/docker/caddy.Dockerfile
    depends_on:
      - php
    ports:
      - "8080:8080"
    volumes:
      - ./etc/caddy/Caddyfile.dev:/etc/Caddyfile
    logging:
      options:
        max-size: 50m
