version: '3.3'

services:
  redis:
    image: redis
    expose:
      - "6379"
    volumes:
      - ./etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - mwop_net_redis:/data
    logging:
      options:
        max-size: 50m

  php:
    build: 
      context: .
      dockerfile: etc/docker/php.Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "9001:9001"
    volumes:
      - .:/var/www
      - ./etc/php/mwop.ini:/usr/local/etc/php/conf.d/mwop.ini
      - ./etc/cron.d/mwopnet:/etc/cron.d/mwopnet
      - ./bin/php-entrypoint:/usr/local/bin/entrypoint
    logging:
      options:
        max-size: 50m

volumes:
  mwop_net_redis:
